language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: VkEplqySoDrjLZKrh3cUckPv4tvoub8jY0iZsudqGORcCtGTtAYthtWlOH7vZhh9o/rmOVA5jmSJh0BrfTTZrCLHH8Rx3PoGp8Ht09n8KpyCE9A3NWBThKhqYRObeWebMsnNoc9LLN+yJeSVE4CQyAlfDNYA/bBEIimA+XPmGbM=
  - secure: WPVmo8nVa2tFCwsQnB3JTqEpGDWJiy/GNeVkkUfqlZyM+VVK/mmPEJw1uRj1KvjzR+ObbC3oHOwrFIX9fMZ/i8IV9fdRxUTNe8aacmUqZobsu8UTDoxJ7fFl8YmzJE89/agxThj8zoJ1kYijcKX436YlP7WxWifEf6iPMD0DcOs=
after_success: curl -T * ftp://$FTP_USER:$FTP_PASSWORD@ftp.beta.nitrotasks.com/beta.nitrotasks.com/
