language: node_js
node_js:
- '8'
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  global:
  - NODE_ENV=travis CXX=g++-4.8
  - CC_TEST_REPORTER_ID=416110cef9815baac2d3dd8d0d3ec8402c977f2a81db6f22092470ed597c6b22
  - secure: 0+3G//oZkBmtLN07pyeP1PCmYbXw+JACK75ASllfcUHqgurmgp66oBjB7vQeExHom4cG8lQAYTC2PEeOsZUV6dAsmuCRXxk3CzJZsx5o74IcVWRp7Noc9eKONpO0jeLKmvTHM/wL38SWjvz1UafZQumOAcAn0lmObZEyVwazjGQ=
  - secure: N7RYw+dTFuxqIH/dxGSSDmr1Oo+7fzCo4dDQonx+K0IrhNpIhIQijtoSlE9re9m6E/N92POE5AgjS2tiFHxwO3sIGCVJQqJea6ew8FFBrKW0MH2R81ExAgSY0I4XEpXsNQEBNAjfiVFsxhNn9XpOJAcW7J8Xi6AwSwAbFKBHzus=
  - secure: E8Dt4HpKPTZuBGYiqDP5v9osa4Rr0HETaA6gdSCjkBXzoA7QpFhTWawje+JnhrGo7euHo2ej5XBpyKeuCbuD5B+pJ8O+G/k33ANp1Pf+vyjNHSOvu00GxS9ZdHPPBgHUpgxswwKjVyXZugdHaj3OHJQCVl4DwzmAm5Il0UjHXZ4=
  - secure: sbntLUoX9uPc+5Z+qDvwL4+7sKyEwHReprydzzoyeuDysK0yj8Vel0OWjJyAelw3GUs3Er3P60BIIZ/tOqmZDEkJhcEsZ+ed7L5O0yOdImCSwDxqoTn2dHyefwhT/xgKDjTXE8WhxSiETNstsZ/CuLAAwtowpbBNcj4KNZVKKTw=
  - secure: IV1CDaUSxyo2M5nvgk4iqkCaCL39jT1klFTz9FTTOKhLyGiA/+1S1+06jNgRQcsLugqUwgE8NCLIlDB0tvJt4HGwVGdgjBUSdcqojIwb00pab+ZRxZBXc/bwIERA4OmyhO5710i4ew/L0uB5ZjvY9rns8ULrhHYnTYEHvqCHK+w=
sudo: required
services:
- docker
before_install:
- docker build ./ -t dymajo/nitro-client:latest
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_deploy:
- openssl aes-256-cbc -K $encrypted_5ec73d8d083e_key -iv $encrypted_5ec73d8d083e_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: npm run docker-push-master
  on:
    branch: master
- provider: script
  script: npm run ssh-remote
  on:
    branch: master
